### ISSUE TITLE
Console spamming "Could not pass event UseBlockEvent to WorldGuard v7.0.10+d9424b1" ever since updating to 1.21

### ISSUE THREAD

**Issue by FlyingGMM** [EngineHub/WorldGuard#2117]
### WorldEdit Version

7.3.5

### WorldGuard Version

7.0.10-dist

### Platform Version

Purpur 1.21-2275-82ccc76

### Confirmations

- [X] I am using the most recent Minecraft release.
- [X] I am using a version of WorldEdit compatible with my Minecraft version.
- [X] I am using a version of WorldGuard compatible with my Minecraft version.
- [X] I am using the latest or recommended version of my platform software.
- [X] I am NOT using a hybrid server, e.g. a server that combines Bukkit and Forge. Examples include Arclight, Mohist, and Cardboard.
- [x] I am NOT using a fork of WorldEdit, such as FastAsyncWorldEdit (FAWE) or AsyncWorldEdit (AWE)

### Bug Description

Ever since updating to 1.21 a few minutes ago, console has been spamming the following error message, even with no one online:
```
Could not pass event UseBlockEvent to WorldGuard v7.0.10+d9424b1
java.lang.NoClassDefFoundError: Could not initialize class com.sk89q.worldguard.bukkit.util.Materials
    at worldguard-bukkit-7.0.10-dist.jar//com.sk89q.worldguard.bukkit.listener.RegionProtectionListener.lambda$onUseBlock$2(RegionProtectionListener.java:256)
    at com.google.common.base.Predicate.test(Predicate.java:79)
    at worldguard-bukkit-7.0.10-dist.jar//com.sk89q.worldguard.bukkit.event.block.AbstractBlockEvent.filterInternal(AbstractBlockEvent.java:132)
    at worldguard-bukkit-7.0.10-dist.jar//com.sk89q.worldguard.bukkit.event.block.AbstractBlockEvent.filter(AbstractBlockEvent.java:124)
    at worldguard-bukkit-7.0.10-dist.jar//com.sk89q.worldguard.bukkit.event.block.UseBlockEvent.filter(UseBlockEvent.java:39)
    at worldguard-bukkit-7.0.10-dist.jar//com.sk89q.worldguard.bukkit.event.block.AbstractBlockEvent.filter(AbstractBlockEvent.java:160)
    at worldguard-bukkit-7.0.10-dist.jar//com.sk89q.worldguard.bukkit.event.block.UseBlockEvent.filter(UseBlockEvent.java:39)
    at worldguard-bukkit-7.0.10-dist.jar//com.sk89q.worldguard.bukkit.listener.RegionProtectionListener.onUseBlock(RegionProtectionListener.java:251)
    at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor119.execute(Unknown Source)
    at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77)
    at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80)
    at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
    at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54)
    at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:131)
    at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:628)
    at worldguard-bukkit-7.0.10-dist.jar//com.sk89q.worldguard.bukkit.util.Events.fireAndTestCancel(Events.java:60)
    at worldguard-bukkit-7.0.10-dist.jar//com.
```

### Expected Behavior

WorldGuard is expected to not do this, I think. It would be nice to solve the underlying issue though.

### Reproduction Steps

1. Update to 1.21
2. Check console

**Comment by me4502** [comment]
Don’t lie on the issue template, use the right version

**Comment by FlyingGMM** [comment]
The right version of what? This is what it told me for the version of each program.

**Comment by Tizooo** [comment]
same issue here
![image](https://github.com/user-attachments/assets/b894f798-d61f-481b-86ba-4bc732098e2d)
